language: scala

scala:
  - 2.13.1

jdk:
  - openjdk8

sudo: false

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - "test -z \"$encrypted_a4dfa378d7fb_key\" || (openssl aes-256-cbc -K $encrypted_a4dfa378d7fb_key -iv $encrypted_a4dfa378d7fb_iv -in project/secrets.tar.enc -out project/secrets.tar -d && tar -xf project/secrets.tar -C project)"

stages:
  - name: lint
  - name: test
  - name: publish
    if: branch = master AND type = push

jobs:
  include:
    - stage: lint
      name: "Check source code formatting"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Build and test for Scala 2.13"
      before_script: gpg --import project/ci.asc
      script: sbt ++$TRAVIS_SCALA_VERSION test package packageSrc publishLocal
    - <<: *test
      scala: 2.11.12
      name: "Build and test for Scala 2.11"
    - <<: *test
      scala: 2.12.10
      name: "Build and test for Scala 2.12"
    - &publish
      stage: publish
      name: "Publish"
      before_script: gpg --import project/ci.asc
      script: sbt +publish sonatypeBundleReleaseIfNotSnapshot

env:
  global:
    - secure: "EP+TqwJLkhfvlbTHhgwSLb5Ue8Tr9MvcRiOuf5zFGh5hUyq4Ou947gJg+Hy5i/qmwEJyx0jVdAdzES7s5A7TfEMc8L89Z4BGadVZfFZkzKhxEnh0wkjeXrYMgUQ/uDq/N4Al1TDZlDzSYLv8hNX4UIn4XKi1g+kGFU+RmPc/zGlqKy9lbwQaIPZV+B5l8BaPmcaxF4zzRHT9Ie1ZHXYQq9C4nPRFoOq5i96dH28jTf4K43uXI6cpmitDCCWyO2JK9Ir0qcvpdPz+fJU+eI3qYkA26lVynynPOCrbDpqtGheuY/7qD4vJqgaG3Qa8SvC6XoshGghVvK4haR1D8316c/p9m1YL5z7B5dpvRsyOSoJDsr9PYufow8pBo4kfglSfvCJ1s8iPneRgZkFNtNTUrarg7Btvl8+nZrEvyoVLCNYyblGPWFVHuEAC/Y2wJy05f7CXzAhGobWoyARcn4suiTY/kc2cP0yAzDRPSwYr6Moa8TNIDdS2sW96NwoSYkdXkn1So+jR2FLpp37MxlUJ0eRBAhCxVe+Oar2lx6JlLyOMpNAUx+HenVLWRIJLAVxLF13Ql5/1Hqk4MUeiKu6sbbCJwN4dVrnzr0mjMIHHP+bDqOeB4bnt1O0UYEU4b+1HXolU7KSXqJjQeeVDKwrYbAi5HvxrvUi5XQK0qH0tjZU="
    - secure: "uLTRH03wNYDbryC5NNQIvaH6tkwWpeNWS82NZHcMwVAyMdD4nn9VoQ89wn8l1BI62F74cVHp4FiYpohPBHb70b7C77ElViRsjIKvt83vEA8PnkJWl0dJBq/tb5S4pq/rqbYS5cRrxTiMO4bMIjoZQDlKHhxS/4lZ1BnFvVNG640zQ4sjwjkmDVoNiIMCVauGucKY0hUjBZg9PBo6TD58fk2Jl8iM3S1NYXWxiqbtn2eXHNEhruiS+KE7nSkgp59XHM/DMP6L5PE257MJDqQCArJ4/BRbdwE/533+xcF1C265g0Om0D70T0nxGHYP3HaRvrIF9jZkm1XLqn0zww9A7DEtXEJvV0gHtptNyN+w9uIJgQ6u9CF6UqHrez0nHwB8cw1qa5vubh1cL4GHjPAWh4+V/J2CQ6i1TxG+R811K9n18fkpliH20icGC46VEdO17FcOgx+TSxo2CFm0vWZSYmLUM5FAMtFY/04Ex1UnsoE2jO10g6sYWD0MbLj9TS2WuZI0jZOKUy3ukMur/P9jV8bW3XZ/7NW387i9SYgpG2nLbHjGFDgjXKsyHzkUXW8cqvq+3lYHVrARrNGoAvtILZi6GzOmQKtkeGyvRQHPwgUU2++3lhSYz68oD4N2OuSB3Pjiu/vJXqWuYoSVb+gKZkJks2eqNYuDRhX/Qp0YmiA="
